name: Scrape Company Data

on:
  schedule:
    - cron: "0 * * * *" # Run every hour

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file if needed

      - name: Run script to scrape data
        run: python webscrap.py  # Replace with your script filename

      - name: Commit changes
        run: |
          git config --global user.email "a.baske86@gmail.com"
          git config --global user.name "AbhishekBaske"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated data update"  # Commit only if changes are detected
          git remote add origin_with_token https://AbhishekBaske:${{ secrets.PAT_ACCESS_TOKEN }}@github.com/AbhishekBaske/marketcap_webscrap.git
          git push origin_with_token main
